// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cpoWp-boYqY9xZhFTRZSZb0T2G4b2TY',
    appId: '1:1037723831450:web:daa596e5f27b028c882323',
    messagingSenderId: '1037723831450',
    projectId: 'pengingat-jadwal-kuliah-c8e8e',
    authDomain: 'pengingat-jadwal-kuliah-c8e8e.firebaseapp.com',
    storageBucket: 'pengingat-jadwal-kuliah-c8e8e.appspot.com',
    measurementId: 'G-J80KQBD93W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pb132eVioAr7W5gWFxjCjSbU5Esphi4',
    appId: '1:1037723831450:android:d3dcc7f6a09a4c01882323',
    messagingSenderId: '1037723831450',
    projectId: 'pengingat-jadwal-kuliah-c8e8e',
    storageBucket: 'pengingat-jadwal-kuliah-c8e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOCGhizz-uIA2Ol2b-Rnjs1DD3DJjrnY',
    appId: '1:1037723831450:ios:84a665d4780e3901882323',
    messagingSenderId: '1037723831450',
    projectId: 'pengingat-jadwal-kuliah-c8e8e',
    storageBucket: 'pengingat-jadwal-kuliah-c8e8e.appspot.com',
    iosBundleId: 'com.example.utsAplikasipengingatjadwalkuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtOCGhizz-uIA2Ol2b-Rnjs1DD3DJjrnY',
    appId: '1:1037723831450:ios:84a665d4780e3901882323',
    messagingSenderId: '1037723831450',
    projectId: 'pengingat-jadwal-kuliah-c8e8e',
    storageBucket: 'pengingat-jadwal-kuliah-c8e8e.appspot.com',
    iosBundleId: 'com.example.utsAplikasipengingatjadwalkuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9cpoWp-boYqY9xZhFTRZSZb0T2G4b2TY',
    appId: '1:1037723831450:web:47345faf22e455cf882323',
    messagingSenderId: '1037723831450',
    projectId: 'pengingat-jadwal-kuliah-c8e8e',
    authDomain: 'pengingat-jadwal-kuliah-c8e8e.firebaseapp.com',
    storageBucket: 'pengingat-jadwal-kuliah-c8e8e.appspot.com',
    measurementId: 'G-DXJW5VJGBZ',
  );
}
